name: 'XML Lint'
description: 'Lint XML files with xmllint'
inputs:
  xml-path:
    description: 'The source (.xml) path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.xml-path }}